### ISSUE TITLE
Keyboard command for inserting not work in Ubuntu

### ISSUE THREAD

**Issue by senpl** [sandy081/vscode-todotasks#49]
In current version insert command no longer working. Single restart not helps.
it says 

> "Running the contributed command:'task.new' failed."

Might be releated with https://github.com/sandy081/vscode-todotasks/issues/41

extension version. v 0.5.0
Ubuntu 18.04 
vscode 
Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-20-generic
log from Log(Extension):
`[exthost] [error] Error: Illegal argument: character must be non-negative
	at Object.t.illegalArgument (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:9:321)
	at new f (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:315:312)
	at new f (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:314:602)
	at DoneTasksDecorator.LineDecorator.getRange (/home/m/.vscode/extensions/sandy081.todotasks-0.5.0/out/src/TodoDocumentDecorator.js:45:39)
	at DoneTasksDecorator.getDoneActionRange (/home/m/.vscode/extensions/sandy081.todotasks-0.5.0/out/src/TodoDocumentDecorator.js:88:42)
	at DoneTasksDecorator.<anonymous> (/home/m/.vscode/extensions/sandy081.todotasks-0.5.0/out/src/TodoDocumentDecorator.js:77:45)
	at Array.forEach (<anonymous>)
	at DoneTasksDecorator.getDecorationTypes (/home/m/.vscode/extensions/sandy081.todotasks-0.5.0/out/src/TodoDocumentDecorator.js:73:15)
	at TaskDecorator.getDecorationTypes (/home/m/.vscode/extensions/sandy081.todotasks-0.5.0/out/src/TodoDocumentDecorator.js:56:57)
	at TodoDocumentEditor.doPerform (/home/m/.vscode/extensions/sandy081.todotasks-0.5.0/out/src/TodoDocumentDecorator.js:29:51)
	at TodoDocumentEditor.performDecoration (/home/m/.vscode/extensions/sandy081.todotasks-0.5.0/out/src/TodoDocumentDecorator.js:23:18)
	at TodoDocumentEditor.insertTask (/home/m/.vscode/extensions/sandy081.todotasks-0.5.0/out/src/TodoDocumentEditor.js:59:63)
	at TodoDocumentEditor.updateTask (/home/m/.vscode/extensions/sandy081.todotasks-0.5.0/out/src/TodoDocumentEditor.js:55:14)
	at TodoDocumentEditor.createNewTask (/home/m/.vscode/extensions/sandy081.todotasks-0.5.0/out/src/TodoDocumentEditor.js:19:14)
	at /home/m/.vscode/extensions/sandy081.todotasks-0.5.0/out/src/TodoCommands.js:12:79
	at t.createApiFactory.C.registerTextEditorCommand.pe.registerCommand.i.edit.e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:668:416)
	at f.edit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:429:377)
	at t.createApiFactory.C.registerTextEditorCommand.pe.registerCommand.r (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:668:390)
	at d._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:457:160)
	at d.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:457:534)
	at h._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:593:118)
	at h._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:592:777)
	at h._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:591:436)
	at h._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:590:279)
	at define.constructor._protocol.onMessage.e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:588:565)
	at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:43:254)
	at e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:39:64)
	at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:43:254)
	at s (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:168:754)
	at Socket.define.constructor._socketDataListener.e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:168:960)
	at Socket.emit (events.js:182:13)
	at Socket.EventEmitter.emit (domain.js:442:20)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20) task.new`

**Comment by senpl** [comment]
Quick fix is install extensions vsc-tasks and convert task set to new shortcut like "ctrl+enter ctrl+enter"
